# Generated by Django 3.0 on 2019-12-22 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_auto_20191222_0752'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentGrades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject1', models.CharField(default='', max_length=150)),
                ('internal1', models.IntegerField(default=0)),
                ('final1', models.IntegerField(default=0)),
                ('subject2', models.CharField(default='', max_length=150)),
                ('internal2', models.IntegerField(default=0)),
                ('final2', models.IntegerField(default=0)),
                ('subject3', models.CharField(default='', max_length=150)),
                ('internal3', models.IntegerField(default=0)),
                ('final3', models.IntegerField(default=0)),
                ('subject4', models.CharField(default='', max_length=150)),
                ('internal4', models.IntegerField(default=0)),
                ('final4', models.IntegerField(default=0)),
                ('subject5', models.CharField(default='', max_length=150)),
                ('internal5', models.IntegerField(default=0)),
                ('final5', models.IntegerField(default=0)),
                ('subject6', models.CharField(default='', max_length=150)),
                ('internal6', models.IntegerField(default=0)),
                ('final6', models.IntegerField(default=0)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='StudentGrades', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
